import type { Restaurant } from "@/lib/types";

export const mockRestaurants: Restaurant[] = [
  {
    id: "1",
    name: "맛있는 돈까스",
    type: "일식 / 돈까스",
    rating: 4.5,
    reviewCount: 1234,
    blogReviewCount: 89,
    walkingTime: 5,
    distance: 85,
    tags: ["점심특선", "혼밥", "가성비"],
    image:
      "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=800&q=80",
    hasParking: true,
    hasGroupSeating: false,
    petFriendly: false,
    reviews: [
      {
        id: "r1",
        author: "맛집탐험가",
        content:
          "돈까스가 정말 바삭바삭하고 맛있어요! 소스도 직접 만드신다고 하네요.",
        rating: 5,
        date: "2024.01.15",
        source: "naver",
      },
      {
        id: "r2",
        author: "점심러버",
        content: "가성비 최고입니다. 양도 많고 맛도 좋아요.",
        rating: 4,
        date: "2024.01.10",
        source: "blog",
      },
    ],
  },
  {
    id: "2",
    name: "청담 파스타",
    type: "양식 / 이탈리안",
    rating: 4.7,
    reviewCount: 856,
    blogReviewCount: 156,
    walkingTime: 8,
    distance: 150,
    tags: ["데이트", "분위기좋음", "와인"],
    image:
      "https://images.unsplash.com/photo-1473093295043-cdd812d0e601?w=800&q=80",
    hasParking: true,
    hasGroupSeating: true,
    petFriendly: false,
    reviews: [
      {
        id: "r3",
        author: "파스타마니아",
        content: "크림파스타 강추! 면이 정말 쫄깃해요.",
        rating: 5,
        date: "2024.01.18",
        source: "naver",
      },
      {
        id: "r4",
        author: "와인소믈리에",
        content: "와인 셀렉션이 좋고 음식과 잘 어울려요.",
        rating: 5,
        date: "2024.01.12",
        source: "instagram",
      },
    ],
  },
  {
    id: "3",
    name: "진짜 짬뽕",
    type: "중식 / 짬뽕 전문",
    rating: 4.3,
    reviewCount: 2341,
    blogReviewCount: 234,
    walkingTime: 3,
    distance: 50,
    tags: ["매운맛", "푸짐함", "빠른배송"],
    image:
      "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=800&q=80",
    hasParking: false,
    hasGroupSeating: true,
    petFriendly: false,
    reviews: [
      {
        id: "r5",
        author: "짬뽕러버",
        content: "국물이 시원하고 해산물이 푸짐해요!",
        rating: 5,
        date: "2024.01.20",
        source: "naver",
      },
      {
        id: "r6",
        author: "중식파",
        content: "짜장면도 맛있어요. 단무지 무한리필!",
        rating: 4,
        date: "2024.01.17",
        source: "blog",
      },
    ],
  },
  {
    id: "4",
    name: "할머니 순두부",
    type: "한식 / 순두부찌개",
    rating: 4.8,
    reviewCount: 3456,
    blogReviewCount: 312,
    walkingTime: 7,
    distance: 120,
    tags: ["전통맛", "든든함", "반찬맛집"],
    image:
      "https://images.unsplash.com/photo-1498654896293-37aacf113fd9?w=800&q=80",
    hasParking: true,
    hasGroupSeating: true,
    petFriendly: false,
    reviews: [
      {
        id: "r7",
        author: "한식매니아",
        content: "순두부가 정말 부드럽고 얼큰해요!",
        rating: 5,
        date: "2024.01.19",
        source: "naver",
      },
      {
        id: "r8",
        author: "반찬탐험가",
        content: "반찬들이 정말 정성스러워요.",
        rating: 5,
        date: "2024.01.14",
        source: "blog",
      },
    ],
  },
  {
    id: "5",
    name: "교대 스시",
    type: "일식 / 초밥",
    rating: 4.6,
    reviewCount: 987,
    blogReviewCount: 178,
    walkingTime: 10,
    distance: 200,
    tags: ["신선함", "오마카세", "기념일"],
    image:
      "https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=800&q=80",
    hasParking: true,
    hasGroupSeating: false,
    petFriendly: false,
    reviews: [
      {
        id: "r9",
        author: "스시러버",
        content: "회가 정말 신선해요. 셰프님이 친절하세요.",
        rating: 5,
        date: "2024.01.21",
        source: "naver",
      },
      {
        id: "r10",
        author: "일식파",
        content: "오마카세 코스 강추합니다!",
        rating: 5,
        date: "2024.01.16",
        source: "instagram",
      },
    ],
  },
  {
    id: "6",
    name: "강남 치킨",
    type: "한식 / 치킨",
    rating: 4.4,
    reviewCount: 5678,
    blogReviewCount: 456,
    walkingTime: 6,
    distance: 100,
    tags: ["바삭함", "맥주", "야식"],
    image:
      "https://images.unsplash.com/photo-1626645738196-c2a7c87a8f58?w=800&q=80",
    hasParking: false,
    hasGroupSeating: true,
    petFriendly: true,
    reviews: [
      {
        id: "r11",
        author: "치킨마니아",
        content: "치킨이 정말 바삭바삭해요!",
        rating: 5,
        date: "2024.01.22",
        source: "naver",
      },
      {
        id: "r12",
        author: "맥주러버",
        content: "맥주와 찰떡궁합!",
        rating: 4,
        date: "2024.01.18",
        source: "blog",
      },
    ],
  },
  {
    id: "7",
    name: "베트남 쌀국수",
    type: "아시안 / 베트남",
    rating: 4.2,
    reviewCount: 1567,
    blogReviewCount: 123,
    walkingTime: 4,
    distance: 70,
    tags: ["건강식", "가벼운식사", "혼밥"],
    image:
      "https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?w=800&q=80",
    hasParking: false,
    hasGroupSeating: false,
    petFriendly: true,
    reviews: [
      {
        id: "r13",
        author: "아시안푸드",
        content: "국물이 진하고 면이 쫄깃해요.",
        rating: 4,
        date: "2024.01.23",
        source: "naver",
      },
      {
        id: "r14",
        author: "건강식러버",
        content: "가볍게 먹기 좋아요!",
        rating: 4,
        date: "2024.01.19",
        source: "instagram",
      },
    ],
  },
  {
    id: "8",
    name: "서울 불고기",
    type: "한식 / 불고기",
    rating: 4.5,
    reviewCount: 2890,
    blogReviewCount: 267,
    walkingTime: 9,
    distance: 180,
    tags: ["회식", "가족모임", "푸짐함"],
    image:
      "https://images.unsplash.com/photo-1590301157890-4810ed352733?w=800&q=80",
    hasParking: true,
    hasGroupSeating: true,
    petFriendly: false,
    reviews: [
      {
        id: "r15",
        author: "불고기매니아",
        content: "불고기가 정말 달콤하고 맛있어요!",
        rating: 5,
        date: "2024.01.24",
        source: "naver",
      },
      {
        id: "r16",
        author: "가족모임",
        content: "단체로 오기 좋아요.",
        rating: 5,
        date: "2024.01.20",
        source: "blog",
      },
    ],
  },
  {
    id: "9",
    name: "명동 칼국수",
    type: "한식 / 칼국수",
    rating: 4.6,
    reviewCount: 4567,
    blogReviewCount: 389,
    walkingTime: 5,
    distance: 90,
    tags: ["수제면", "전통맛", "든든함"],
    image:
      "https://images.unsplash.com/photo-1607013407627-6ee814329547?w=800&q=80",
    hasParking: false,
    hasGroupSeating: true,
    petFriendly: false,
    reviews: [
      {
        id: "r17",
        author: "칼국수마니아",
        content: "면이 정말 쫄깃하고 국물이 진해요!",
        rating: 5,
        date: "2024.01.25",
        source: "naver",
      },
      {
        id: "r18",
        author: "한식파",
        content: "만두도 꼭 시켜보세요!",
        rating: 5,
        date: "2024.01.21",
        source: "blog",
      },
    ],
  },
  {
    id: "10",
    name: "홍대 타코",
    type: "멕시칸 / 타코",
    rating: 4.3,
    reviewCount: 876,
    blogReviewCount: 98,
    walkingTime: 12,
    distance: 240,
    tags: ["이색음식", "매운맛", "데이트"],
    image:
      "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=800&q=80",
    hasParking: false,
    hasGroupSeating: false,
    petFriendly: true,
    reviews: [
      {
        id: "r19",
        author: "타코러버",
        content: "정말 맛있는 타코예요! 소스가 특별해요.",
        rating: 5,
        date: "2024.01.26",
        source: "naver",
      },
      {
        id: "r20",
        author: "멕시칸푸드",
        content: "나쵸도 강추합니다!",
        rating: 4,
        date: "2024.01.22",
        source: "instagram",
      },
    ],
  },
  {
    id: "11",
    name: "이태원 버거",
    type: "양식 / 햄버거",
    rating: 4.7,
    reviewCount: 2345,
    blogReviewCount: 234,
    walkingTime: 8,
    distance: 160,
    tags: ["수제버거", "푸짐함", "맥주"],
    image:
      "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&q=80",
    hasParking: true,
    hasGroupSeating: true,
    petFriendly: false,
    reviews: [
      {
        id: "r21",
        author: "버거마니아",
        content: "패티가 두툼하고 육즙이 살아있어요!",
        rating: 5,
        date: "2024.01.27",
        source: "naver",
      },
      {
        id: "r22",
        author: "수제버거러버",
        content: "감자튀김도 맛있어요!",
        rating: 5,
        date: "2024.01.23",
        source: "blog",
      },
    ],
  },
  {
    id: "12",
    name: "종로 삼계탕",
    type: "한식 / 삼계탕",
    rating: 4.8,
    reviewCount: 3456,
    blogReviewCount: 345,
    walkingTime: 7,
    distance: 130,
    tags: ["보양식", "전통맛", "여름특선"],
    image:
      "https://images.unsplash.com/photo-1498654896293-37aacf113fd9?w=800&q=80",
    hasParking: false,
    hasGroupSeating: true,
    petFriendly: false,
    reviews: [
      {
        id: "r23",
        author: "보양식매니아",
        content: "삼계탕이 정말 진하고 맛있어요!",
        rating: 5,
        date: "2024.01.28",
        source: "naver",
      },
      {
        id: "r24",
        author: "한식파",
        content: "인삼주도 꼭 드셔보세요!",
        rating: 5,
        date: "2024.01.24",
        source: "blog",
      },
    ],
  },
  {
    id: "13",
    name: "역삼 곱창골목",
    type: "한식 / 곱창·막창",
    rating: 4.4,
    reviewCount: 1892,
    blogReviewCount: 201,
    walkingTime: 4,
    distance: 65,
    tags: ["야식", "소주", "회식"],
    image:
      "https://images.unsplash.com/photo-1529694157872-4e0c0f3b238b?w=800&q=80",
    hasParking: true,
    hasGroupSeating: true,
    petFriendly: false,
    reviews: [
      {
        id: "r25",
        author: "곱창러버",
        content: "곱창이 쫄깃하고 양념이 일품이에요.",
        rating: 5,
        date: "2024.01.29",
        source: "naver",
      },
      {
        id: "r26",
        author: "야식탐험",
        content: "막창도 꼭 드셔보세요!",
        rating: 4,
        date: "2024.01.25",
        source: "blog",
      },
    ],
  },
  {
    id: "14",
    name: "선릉 카레",
    type: "일식 / 카레",
    rating: 4.5,
    reviewCount: 1123,
    blogReviewCount: 134,
    walkingTime: 6,
    distance: 95,
    tags: ["혼밥", "점심특선", "가성비"],
    image:
      "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=800&q=80",
    hasParking: false,
    hasGroupSeating: false,
    petFriendly: false,
    reviews: [
      {
        id: "r27",
        author: "카레마니아",
        content: "진한 카레와 크리스피 치킨 카츠 조합!",
        rating: 5,
        date: "2024.01.30",
        source: "naver",
      },
      {
        id: "r28",
        author: "점심러버",
        content: "점심에 딱 좋은 한 그릇.",
        rating: 4,
        date: "2024.01.26",
        source: "instagram",
      },
    ],
  },
  {
    id: "15",
    name: "논현 떡볶이집",
    type: "한식 / 분식",
    rating: 4.2,
    reviewCount: 4231,
    blogReviewCount: 512,
    walkingTime: 3,
    distance: 45,
    tags: ["매운맛", "가성비", "스낵"],
    image:
      "https://images.unsplash.com/photo-1585032226651-759b368d7246?w=800&q=80",
    hasParking: false,
    hasGroupSeating: true,
    petFriendly: true,
    reviews: [
      {
        id: "r29",
        author: "떡볶이왕",
        content: "옛날 떡볶이 맛 나요. 떡이 쫄깃해요.",
        rating: 4,
        date: "2024.01.31",
        source: "naver",
      },
      {
        id: "r30",
        author: "분식러버",
        content: "순대와 튀김도 맛있어요!",
        rating: 5,
        date: "2024.01.27",
        source: "blog",
      },
    ],
  },
  {
    id: "16",
    name: "서초 한정식",
    type: "한식 / 한정식",
    rating: 4.9,
    reviewCount: 567,
    blogReviewCount: 198,
    walkingTime: 11,
    distance: 220,
    tags: ["특별한날", "코스요리", "분위기"],
    image:
      "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&q=80",
    hasParking: true,
    hasGroupSeating: true,
    petFriendly: false,
    reviews: [
      {
        id: "r31",
        author: "한정식매니아",
        content: "코스 하나하나 정성이 느껴져요.",
        rating: 5,
        date: "2024.02.01",
        source: "naver",
      },
      {
        id: "r32",
        author: "데이트코스",
        content: "기념일 추천합니다!",
        rating: 5,
        date: "2024.01.28",
        source: "blog",
      },
    ],
  },
  {
    id: "17",
    name: "방배 동남아음식",
    type: "아시안 / 태국·베트남",
    rating: 4.3,
    reviewCount: 876,
    blogReviewCount: 87,
    walkingTime: 8,
    distance: 140,
    tags: ["매운맛", "이색음식", "쌀국수"],
    image:
      "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=800&q=80",
    hasParking: true,
    hasGroupSeating: true,
    petFriendly: false,
    reviews: [
      {
        id: "r33",
        author: "동남아푸드",
        content: "팟타이랑 똠얌꿍 맛있어요!",
        rating: 5,
        date: "2024.02.02",
        source: "naver",
      },
      {
        id: "r34",
        author: "아시안러버",
        content: "매운맛 조절 가능해요.",
        rating: 4,
        date: "2024.01.29",
        source: "instagram",
      },
    ],
  },
  {
    id: "18",
    name: "반포 수제비",
    type: "한식 / 수제비·칼국수",
    rating: 4.6,
    reviewCount: 2345,
    blogReviewCount: 276,
    walkingTime: 5,
    distance: 80,
    tags: ["전통맛", "든든함", "날씨쌀쌀할때"],
    image:
      "https://images.unsplash.com/photo-1555126634-323283e090fa?w=800&q=80",
    hasParking: false,
    hasGroupSeating: true,
    petFriendly: false,
    reviews: [
      {
        id: "r35",
        author: "수제비마니아",
        content: "국물이 진하고 수제비가 쫄깃해요.",
        rating: 5,
        date: "2024.02.03",
        source: "naver",
      },
      {
        id: "r36",
        author: "한식파",
        content: "만두 넣은 거 강추!",
        rating: 5,
        date: "2024.01.30",
        source: "blog",
      },
    ],
  },
  {
    id: "19",
    name: "잠실 피자",
    type: "양식 / 피자",
    rating: 4.5,
    reviewCount: 1678,
    blogReviewCount: 223,
    walkingTime: 7,
    distance: 115,
    tags: ["데이트", "가족모임", "치즈"],
    image:
      "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&q=80",
    hasParking: true,
    hasGroupSeating: true,
    petFriendly: true,
    reviews: [
      {
        id: "r37",
        author: "피자러버",
        content: "도우가 바삭하고 치즈가 엄청나요!",
        rating: 5,
        date: "2024.02.04",
        source: "naver",
      },
      {
        id: "r38",
        author: "치즈매니아",
        content: "콤보 피자 추천합니다.",
        rating: 4,
        date: "2024.01.31",
        source: "blog",
      },
    ],
  },
  {
    id: "20",
    name: "성수 브런치카페",
    type: "카페·브런치",
    rating: 4.7,
    reviewCount: 3456,
    blogReviewCount: 445,
    walkingTime: 6,
    distance: 98,
    tags: ["브런치", "인스타감성", "베이글"],
    image:
      "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80",
    hasParking: true,
    hasGroupSeating: true,
    petFriendly: true,
    reviews: [
      {
        id: "r39",
        author: "브런치러버",
        content: "에그베네딕트 진짜 맛있어요!",
        rating: 5,
        date: "2024.02.05",
        source: "naver",
      },
      {
        id: "r40",
        author: "카페탐험",
        content: "커피도 좋고 분위기 최고.",
        rating: 5,
        date: "2024.02.01",
        source: "instagram",
      },
    ],
  },
  {
    id: "21",
    name: "건대 닭갈비",
    type: "한식 / 닭갈비",
    rating: 4.4,
    reviewCount: 2890,
    blogReviewCount: 312,
    walkingTime: 4,
    distance: 72,
    tags: ["치즈닭갈비", "푸짐함", "학생인기"],
    image:
      "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=800&q=80",
    hasParking: false,
    hasGroupSeating: true,
    petFriendly: false,
    reviews: [
      {
        id: "r41",
        author: "닭갈비왕",
        content: "치즈 넣으면 환상의 조합!",
        rating: 5,
        date: "2024.02.06",
        source: "naver",
      },
      {
        id: "r42",
        author: "건대맛집",
        content: "가성비 좋고 양 많아요.",
        rating: 4,
        date: "2024.02.02",
        source: "blog",
      },
    ],
  },
  {
    id: "22",
    name: "여의도 회식당",
    type: "일식 / 회·해산물",
    rating: 4.8,
    reviewCount: 1234,
    blogReviewCount: 167,
    walkingTime: 9,
    distance: 175,
    tags: ["회", "신선함", "회식"],
    image:
      "https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=800&q=80",
    hasParking: true,
    hasGroupSeating: true,
    petFriendly: false,
    reviews: [
      {
        id: "r43",
        author: "회매니아",
        content: "회가 정말 신선하고 다양해요.",
        rating: 5,
        date: "2024.02.07",
        source: "naver",
      },
      {
        id: "r44",
        author: "해산물러버",
        content: "연회 코스 추천합니다!",
        rating: 5,
        date: "2024.02.03",
        source: "blog",
      },
    ],
  },
  {
    id: "23",
    name: "마포 감자탕",
    type: "한식 / 감자탕",
    rating: 4.5,
    reviewCount: 3456,
    blogReviewCount: 398,
    walkingTime: 5,
    distance: 88,
    tags: ["뼈해장국", "푸짐함", "밤늦게"],
    image:
      "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800&q=80",
    hasParking: true,
    hasGroupSeating: true,
    petFriendly: false,
    reviews: [
      {
        id: "r45",
        author: "감자탕러버",
        content: "뼈가 푸짐하고 국물이 깔끔해요.",
        rating: 5,
        date: "2024.02.08",
        source: "naver",
      },
      {
        id: "r46",
        author: "해장국파",
        content: "다음날 해장으로 딱!",
        rating: 4,
        date: "2024.02.04",
        source: "instagram",
      },
    ],
  },
  {
    id: "24",
    name: "공덕 샌드위치",
    type: "양식 / 샌드위치·브런치",
    rating: 4.6,
    reviewCount: 987,
    blogReviewCount: 112,
    walkingTime: 3,
    distance: 52,
    tags: ["가벼운식사", "혼밥", "점심특선"],
    image:
      "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=800&q=80",
    hasParking: false,
    hasGroupSeating: false,
    petFriendly: true,
    reviews: [
      {
        id: "r47",
        author: "샌드위치마니아",
        content: "빵이 부드럽고 재료가 신선해요.",
        rating: 5,
        date: "2024.02.09",
        source: "naver",
      },
      {
        id: "r48",
        author: "브런치러버",
        content: "아보카도 에그 샌드위치 강추!",
        rating: 5,
        date: "2024.02.05",
        source: "blog",
      },
    ],
  },
];
